In [1]:

# # Recommended versions
# numpy 	1.26.4
# pandas	2.2.2
# matplotlib	3.7.1
# seaborn	0.10.0
# statsmodels	0.14.4
# sklearn	1.5.2

In [2]:
import pandas as pd
import numpy as np

In [3]:
dib = pd.read_csv('Diabetes Example Data.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'Diabetes Example Data.csv'

In [31]:
dib.head()

   Blood Sugar Level Diabetes
0                190       No
1                240      Yes
2                300      Yes
3                160       No
4                200      Yes

In [32]:
# Converting Yes to 1 and No to 0
dib['Diabetes'] = dib['Diabetes'].map({'Yes': 1, 'No': 0})

In [33]:
dib.head()

   Blood Sugar Level  Diabetes
0                190         0
1                240         1
2                300         1
3                160         0
4                200         1

In [34]:
# Putting feature variable to X
X = dib['Blood Sugar Level']

# Putting response variable to y
y = dib['Diabetes']

In [36]:
import statsmodels.api as sm

In [37]:
logm1 = sm.GLM(y,(sm.add_constant(X)), family = sm.families.Binomial())
logm1.fit().summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                 Generalized Linear Model Regression Results
==============================================================================
Dep. Variable:               Diabetes   No. Observations:                   10
Model:                            GLM   Df Residuals:                        8
Model Family:                Binomial   Df Model:                            1
Link Function:                  logit   Scale:                             1.0
Method:                          IRLS   Log-Likelihood:                -2.5838
Date:                Tue, 06 Mar 2018   Deviance:                       5.1676
Time:                        00:56:36   Pearson chi2:                     4.32
No. Iterations:                     7
=====================================================================================
                        coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------------
const               -13.5243      9.358     -1.445      0.148     -31.866       4.817
Blood Sugar Level     0.0637      0.044      1.439      0.150      -0.023       0.150
=====================================================================================
"""