In [1]:
# Load 

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from statsmodels.stats.outliers_influence import variance_inflation_factor
from sklearn.metrics import r2_score

import statsmodels.api as sm
import warnings
warnings.filterwarnings('ignore')

from sklearn.naive_bayes import GaussianNB, MultinomialNB
from sklearn.metrics import  accuracy_score

# Bernoulli Naive bayes is good at handling boolean/binary attributes 
# Multinomial Naive bayes is good at handling discrete values (Count or frequency based features) 
# Gaussian naive bayes is good at handling continuous values

In [2]:
# Load the Titanic dataset titanic_df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv") 
# titanic_df.head(2)

In [3]:
df  = pd.read_csv("diabetes.csv")

### Ensure we have to performed EDA

In [4]:
df.head()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [5]:
df.shape

(768, 9)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: float64(2), int64(7)
memory usage: 54.1 KB

In [8]:

df["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [12]:
# split data into features X and target Y
X = df.drop('Outcome', axis=1)  # features
y = df['Outcome']  # Target

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y , test_size=0.2, random_state=42)

In [14]:
print(X_train.shape)
print(X_test.shape)

(614, 8)
(154, 8)

In [15]:
nb_model = GaussianNB()

In [16]:
nb_model?

Type:        GaussianNB
String form: GaussianNB()
File:        c:\users\nigam\anaconda3\lib\site-packages\sklearn\naive_bayes.py
Docstring:
Gaussian Naive Bayes (GaussianNB).

Can perform online updates to model parameters via :meth:`partial_fit`.
For details on algorithm used to update feature means and variance online,
see Stanford CS tech report STAN-CS-79-773 by Chan, Golub, and LeVeque:

    http://i.stanford.edu/pub/cstr/reports/cs/tr/79/773/CS-TR-79-773.pdf

Read more in the :ref:`User Guide <gaussian_naive_bayes>`.

Parameters
----------
priors : array-like of shape (n_classes,), default=None
    Prior probabilities of the classes. If specified, the priors are not
    adjusted according to the data.

var_smoothing : float, default=1e-9
    Portion of the largest variance of all features that is added to
    variances for calculation stability.

    .. versionadded:: 0.20

Attributes
----------
class_count_ : ndarray of shape (n_classes,)
    number of training samples observed in each class.

class_prior_ : ndarray of shape (n_classes,)
    probability of each class.

classes_ : ndarray of shape (n_classes,)
    class labels known to the classifier.

epsilon_ : float
    absolute additive value to variances.

n_features_in_ : int
    Number of features seen during :term:`fit`.

    .. versionadded:: 0.24

feature_names_in_ : ndarray of shape (`n_features_in_`,)
    Names of features seen during :term:`fit`. Defined only when `X`
    has feature names that are all strings.

    .. versionadded:: 1.0

var_ : ndarray of shape (n_classes, n_features)
    Variance of each feature per class.

    .. versionadded:: 1.0

theta_ : ndarray of shape (n_classes, n_features)
    mean of each feature per class.

See Also
--------
BernoulliNB : Naive Bayes classifier for multivariate Bernoulli models.
CategoricalNB : Naive Bayes classifier for categorical features.
ComplementNB : Complement Naive Bayes classifier.
MultinomialNB : Naive Bayes classifier for multinomial models.

Examples
--------
>>> import numpy as np
>>> X = np.array([[-1, -1], [-2, -1], [-3, -2], [1, 1], [2, 1], [3, 2]])
>>> Y = np.array([1, 1, 1, 2, 2, 2])
>>> from sklearn.naive_bayes import GaussianNB
>>> clf = GaussianNB()
>>> clf.fit(X, Y)
GaussianNB()
>>> print(clf.predict([[-0.8, -1]]))
[1]
>>> clf_pf = GaussianNB()
>>> clf_pf.partial_fit(X, Y, np.unique(Y))
GaussianNB()
>>> print(clf_pf.predict([[-0.8, -1]]))
[1]

In [18]:
nb_model.fit(X_train, y_train)

GaussianNB()

In [19]:
y_pred_train = nb_model.predict(X_train)
y_pred_test = nb_model.predict(X_test)

In [21]:
print(accuracy_score(y_train, y_pred_train)*100,2)
print(accuracy_score(y_test, y_pred_test)*100,2)

75.2442996742671 2
76.62337662337663 2

### Test Classification

In [22]:
# Sample dataset: text and labels (spam or ham) texts = [ "Free money now!!!", "Hey, are we still meeting tomorrow?", "Congratulations! You've won a free gift card!", "Reminder about your appointment next week", "Urgent! Reply to claim your prize!", "Let's catch up later tonight.", "Exclusive offer for you!", "This is not a spam message." ] # Corresponding labels: 1 for spam, 0 for ham labels = [1, 0, 1, 0, 1, 0, 1, 0]

In [23]:
texts = [ "Free money now!!!", "Hey, are we still meeting tomorrow?", "Congratulations! You've won a free gift card!", "Reminder about your appointment next week", "Urgent! Reply to claim your prize!", "Let's catch up later tonight.", "Exclusive offer for you!", "This is not a spam message." ]

In [25]:
 labels = [1, 0, 1, 0, 1, 0, 1, 0]

In [26]:
from sklearn.feature_extraction.text import CountVectorizer

In [30]:
vec = CountVectorizer()
X = vec.fit_transform(texts) # convert test to features vectors

In [29]:
pd.set_option("display.max_columns", None)
cols = vec.get_feature_names_out()
pd.DataFrame(X.toarray(), columns=cols)

,about,appointment,are,card,catch,claim,congratulations,exclusive,for,free,gift,hey,is,later,let,meeting,message,money,next,not,now,offer,prize,reminder,reply,spam,still,this,to,tomorrow,tonight,up,urgent,ve,we,week,won,you,your
0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0
2,0,0,0,1,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,1,0
3,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1
4,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,1
5,0,0,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0
6,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
7,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0

In [32]:
X_train, X_test, y_train, y_test = train_test_split(X, labels, test_size=0.2, random_state=42)

In [34]:
nb_classifier = MultinomialNB()

In [35]:
nb_classifier.fit(X_train, y_train)

MultinomialNB()

In [36]:
y_pred_train = nb_classifier.predict(X_train)
y_pred_test = nb_classifier.predict(X_test)

In [37]:
y_train

[1, 0, 1, 1, 0, 1]

In [38]:
y_pred_train

array([1, 0, 1, 1, 0, 1])

In [42]:
data = ["Hey You won 1 crore Money"]

In [43]:
x = vec.transform(data)

In [44]:
nb_classifier.predict(x)

array([1])

In [52]:
data = ["Hey Let's catch up"]
x = vec.transform(data)
nb_classifier.predict(x)

array([1])

array([1])